services:
  # nginx:
  #     image: nginx:alpine
  #     container_name: nginx-proxy
  #     ports:
  #       - "80:80"
  #       - "443:443"
  #     volumes:
  #       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #       - ./nginx/conf.d:/etc/nginx/conf.d
  #       - ./ssl:/etc/nginx/ssl  # For SSL certificates
  #     depends_on:
  #       - backend
  #       - frontend
  #     restart: unless-stopped
  #     networks:
  #       - qr-chatbot-network
  backend:
    build: ./backend
    container_name: qr-chatbot-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      # Development hot reload (optional)
      - ./backend:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - qr-chatbot-network

  frontend:
    build: ./frontend
    container_name: qr-chatbot-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=/api
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - qr-chatbot-network

networks:
  qr-chatbot-network:
    driver: bridge